config/routes.rb
Rails.application.routes.draw do
  
  # 404/500 pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :newsletter_emails
  resources :careers
  devise_scope :admin do
    # Redirests signing out users back to sign-in
    get "admins", to: "devise/sessions#new"
  end
  
  devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }

  # homepage
  root "pages#home"
  get 'intro_video_embed', to: "pages#intro_video_embed", as: :embed_video
  get 'intro_video_embed_maint', to: "pages#intro_video_embed_maint", as: :embed_video_maint
  get 'newsletter_confirm', to: "newsletter_emails#confirm", as: :newsletter_confirm

  # Notams
  get 'notams/select_featured', to: 'notams#select_featured_notams'
  post 'uploader/image', to: 'uploader#image' #add upload image to notams 
  get 'webinars', to: 'notams#webinars'
  resources :notams

  # Webinars
  # resources :webinars
  
  # Agreement
  get 'agreements/form2', to: 'agreements#form2', as: :form2 
  resources :agreements

  ### Static pages routes

  # Menu Pages
  get 'marketing-system', to: 'pages#system'
  get 'schedule-call', to: 'pages#schedule_call'
  get 'about-us', to: 'pages#about_us'
  get 'system-video', to: 'pages#system_video'
  get 'flight-school-marketing-checklist', to: 'pages#checklist', as: "checklist"

  # Qualify Quiz
  get 'qualify_quiz', to: "pages#one", as: :quiz_start
  get 'qualify_quiz/two', to: "pages#two", as: :quiz_question_two
  get 'qualify_quiz/three', to: "pages#three", as: :quiz_question_three
  get 'qualify_quiz/four', to: "pages#four", as: :quiz_question_four
  get 'qualify_quiz/qualified', to: "pages#qualified", as: :quiz_qualified
  get 'qualify_quiz/unqualified_CFI', to: "pages#unqualified_CFI", as: :quiz_unqualified_CFI
  get 'qualify_quiz/unqualified_ad', to: "pages#unqualified_ad", as: :quiz_unqualified_ad
  get 'qualify_quiz/unqualified_capacity', to: "pages#unqualified_capacity", as: :quiz_unqualified_capacity
  get 'qualify_quiz/unqualified_service', to: "pages#unqualified_service", as: :quiz_unqualified_service


  # Offering Pages / Services
  get 'website-design', to: 'pages#website_design'
  get 'search-engine-optimization', to: 'pages#search_engine_optimization'
  get 'pay-per-click-ads', to: 'pages#pay_per_click_ads'
  get 'video-creation', to: 'pages#video_creation'
  get 'email-campaigns', to: 'pages#email_campaigns'
  get 'social-media-management', to: 'pages#social_media_management'
  get 'reputation-management', to: 'pages#reputation_management'

  # Legal Footer Pages
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'terms-of-service', to: 'pages#terms_of_service'

end

app/models/notam.rb
class Notam < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :status, inclusion: { :in => ['Published','Drafting']}
  validates :title, presence: true
  validates :category, inclusion: { :in => ['Business and Marketing','Aviation and Flying', 'News and Announcements']}
  validates :notam_date, presence: true
  validates :author, presence: true
  validates :feature_image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg', 'image/webp'], size_range: 1..(2.megabytes) }
  validates :notam_body, presence: true
  validates :featured, inclusion: { :in => ['Yes','No']}
  validates :webinar, inclusion: { :in => ['Yes','No']}
  
  has_one_attached :feature_image

  # Category of blog posts
  scope :business_and_marketing, -> {where(category: "Business and Marketing")}
  scope :aviation_and_flying, -> {where(category: "Aviation and Flying")}
  scope :news_and_announcements, -> {where(category: "News and Announcements")}
  
  # Types of blog posts (Featured / Webinar)
  scope :webinar, -> {where(webinar: "Yes")}
  scope :featured, -> {where(featured: "Yes")}

  # Time reference
  scope :upcoming, -> {where('notam_date >= ?', Time.now)}
  scope :previous, -> {where('notam_date < ?', Time.now)}

  # Status
  scope :draft, -> {where(status: "Drafting")}
  scope :published, -> {where(status: "Published")}


end

app/controllers/notams_controller.rb
class NotamsController < ApplicationController
  before_action :set_notam, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show, :webinars]

  def webinars
    @notams = Notam.webinar
    @newsletter_email = NewsletterEmail.new
  end

  # GET /notams or /notams.json
  def index
    @notams = Notam.all
    @newsletter_email = NewsletterEmail.new
  end

  # GET /notams/1 or /notams/1.json
  def show
    @newsletter_email = NewsletterEmail.new
  end

  # GET /notams/new
  def new
    @notam = Notam.new
    @newsletter_email = NewsletterEmail.new
  end

  # GET /notams/1/edit
  def edit
    @newsletter_email = NewsletterEmail.new
  end

  # POST /notams or /notams.json
  def create
    @notam = Notam.new(notam_params)
    @newsletter_email = NewsletterEmail.new

    respond_to do |format|
      if @notam.save
        format.html { redirect_to notam_url(@notam), notice: "Notam was successfully created." }
        format.json { render :show, status: :created, location: @notam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notams/1 or /notams/1.json
  def update
    @newsletter_email = NewsletterEmail.new
    respond_to do |format|
      if @notam.update(notam_params)
        format.html { redirect_to notam_url(@notam), notice: "Notam was successfully updated." }
        format.json { render :show, status: :ok, location: @notam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notams/1 or /notams/1.json
  def destroy
    @notam.destroy

    respond_to do |format|
      format.html { redirect_to notams_url, notice: "Notam was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notam
      @notam = Notam.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notam_params
      params.require(:notam).permit(:title, :notam_date, :author, :notam_body, :category, :status, :tags, :meta_description, :meta_keywords, :feature_image, :featured, :webinar)
    end
end

app/helpers/notams_helper.rb
module NotamsHelper
end

app/views/notams/_form.html.erb
<%= tinymce_assets %>

<%= form_with(model: notam, class: "contents") do |form| %>
  <% if notam.errors.any? %>
    <div class="px-10 lg:pl-20 lg:pr-20 pb-10" >
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(notam.errors.count, "mistake") %>.  Cannot save. Please Fix.</h2>

        <ul>
          <% notam.errors.each do |error| %>
            <li class="list-disc ml-5"><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <% if current_page?(new_notam_path) %>
    <h1 class="font-bold text-4xl lg:pl-20 lg:text-left text-center">New NOTAM</h1>
  <% else %>
    <h1 class="font-bold text-4xl lg:pl-20 lg:text-left text-center">Edit NOTAM</h1>
  <% end %>

  <div class="flex flex-col lg:flex-row lg:px-10">
    <div class="px-10 lg:w-1/3 pr-10">
      <!--Blog Data-->
      <div class="my-5">
        <%= form.select(:status, ['NOTAM Status','Published','Drafting'],  {}, {:class => 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full'}) %>
      </div>

      <div class="my-5">
        <%= form.select(:category, ['NOTAM Category','Business and Marketing','Aviation and Flying', 'News and Announcements'],  {}, {:class => 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full'}) %>
      </div>

      <div class="my-5">
        <%= form.select(:featured, ['Featured?','Yes','No'],  {}, {:class => 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full'}) %>
      </div>

      <div class="my-5">
        <%= form.select(:webinar, ['Webinar?','Yes','No'],  {}, {:class => 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full'}) %>
      </div>

      <div class="my-5">
        <%= form.text_field :title, placeholder: "NOTAM Title", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.date_field :notam_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.text_field :author, placeholder: "Author", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div> 

      <div class="my-5">
        <%= form.text_area :meta_description, rows: 3, placeholder: "Meta Description", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.text_field :meta_keywords, placeholder: "Meta Keywords", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.file_field :feature_image, class: "text-sm text-grey-500
            file:py-2 file:px-6
            file:rounded-lg file:border-0
            file:text-sm file:font-medium
            file:bg-blue-100 file:text-blue-700
            hover:file:cursor-pointer hover:file:bg-blue-200
            hover:file:text-blue-700" %>
      </div>

      <div class="inline">
        <%= form.submit class: "rounded-lg py-2 px-4 bg-blue-600 hover:bg-blue-800 text-sm text-white inline-block font-medium cursor-pointer", data: { turbo: false } %>
      </div>
    </div>
    <!--Blog editor-->
    <div class="lg:w-2/3 pt-10 lg:pt-0 lg:pl-5 lg:pr-10">
      <div class="lg:my-5">
        <%= form.text_area :notam_body, rows: 30, class: "tinymce block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        <%= tinymce %>
      </div>
    </div>
  </div>
<% end %>

app/views/notams/_notam.html.erb
<div id="<%= dom_id notam %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= notam.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notam date:</strong>
    <%= notam.notam_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Author:</strong>
    <%= notam.author %>
  </p>

  <p class="my-5">
    <%= image_tag notam.feature_image.url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notam body:</strong>
    <div class="no-tailwindcss-base">
      <%= raw notam.notam_body %>
    </div>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this notam", notam, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this notam', edit_notam_path(notam), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium", data: { turbo: false }%>
    <hr class="mt-6">
  <% end %>
</div>

app/views/notams/_notam_category_card.html.erb
        <%= link_to post, data: { turbo: false }, class: "" do%>
          <div class="flex flex-row items-center lg:border-0  w-full lg:rounded-lg h-24 lg:mb-0 hover:brightness-105 transition-all duration-300">
            <!--image-->
            <div class="w-2/5 flex flex-row items-center">
              <%= image_tag post.feature_image.url, class: "object-cover object-center lg:rounded-l-lg h-24 w-full", alt: "picture for article: #{post.title}"%>
              <%#= post.feature_image %><br>    
            </div>
            <div class=" pl-5 w-3/5 flex flex-col items-start justify-center h-full text-md pr-5 bg-slate-50 lg:rounded-r-lg lg:bg-gradient-to-b from-slate-50 to-slate-200  ">
              <div class="line-clamp-2 text-slate-800"><%= post.title %></div>
              <div class="font-semibold text-sm pt-1 text-black">
                <%= I18n.localize(post.notam_date, :format => '%^a %^b %-d %Y') %>
              </div>
            </div>
          </div>
        <% end %>

app/views/notams/edit.html.erb
<%# Head / Meta Data %>
<% title("Publish New NOTAM | Right Rudder Marketing Blog") %>
<% meta_description("Publish a new NOTAM on the Right Rudder Marketing Blog") %>
<% meta_keywords("aviation blog, flight school blog, aviation business blog, news about business aviation, flight school news") %>

<%= render "shared/navbar_nonsticky" %>

<div class="pt-10 lg:py-10 bg-slate-100">

  <%= render "form", notam: @notam %>

  <%#= link_to 'Back to notams', notams_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

<%= render "shared/footer"%>

<!--
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing notam</h1>

  <%#= render "form", notam: @notam %>

  <%#= link_to "Show this notam", @notam, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <#%= link_to "Back to notams", notams_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
-->

app/views/notams/index.html.erb
<%# Head / Meta Data %>
<% title("NOTAMs - The Right Rudder Marketing Blog") %>
<% meta_description("A blog all about flight schools and marketing.  We take a look at digital marketing strategies used in the aviation industry which can help accelerate the number the of student pilots coming to your flight school.") %>
<% meta_keywords("Right Rudder Marketing, Blog, aviation webinar, aviation marketing, aviation business marketing ideas") %>
<% og_image(image_url("rrm-notams-trans.webp")) %>
<% twitter_image(image_url("rrm-notams-trans.webp")) %>


<!--Set Page font size and limit sticky-->
<div class="text-lg bg-gradient-to-r from-slate-100 to-blue-100">
  <%= render "shared/navbar" %>
  <!--Header Section-->
  <section class="grid place-items-center">
    <div class="py-20 flex flex-col lg:flex-row lg:w-5/6">
      <!--Blog image-->
      <div class="grid place-items-center">
        <%= image_tag "rrm-notams-trans.webp", class: "w-3/4"%>
      </div>
      
      <!--Text about blog-->
      <div class="px-5 lg:px-0">
        <h1 class="text-5xl font-bold text-center pt-20 pb-5">Right Rudder Marketing NOTAMs</h1>
        <h2 class=" text-lg lg:text-2xl font-semibold text-center pb-5">An aviation and flying blog.<br>Learn business and marketing.<br>Read the lastest news.</h2>
        <p class="lg:pb-20 text-md px-10 lg:text-xl text-center">The Right Rudder Marketing blog</p>
      </div>
    </div>
  </section>

  <!--Top Section-->
  <div class="flex flex-col lg:flex-row lg:justify-center lg:py-10 bg-gradient-to-r from-slate-700 to-slate-900">
    
    <!--Featured Article-->
    <% @notams.published.featured.limit(1).reverse_each do |feature| %> 
      <%= link_to feature, data: { turbo: false }, class: "w-full w-full lg:w-1/2 h-screen-1/2" do %>
      <section style="background-image: url(<%=feature.feature_image.url%>)" class="h-screen-1/2 bg-cover bg-center flex flex-col justify-end lg:mx-5 lg:rounded-lg">
        <!--Bottom Section of image feature-->
        <div class="bg-gradient-to-r from-slate-50/50 to-slate-50/50 px-10 py-5 hover:from-slate-50/60 hover:to-slate-50/60 transition-all duration-300 lg:rounded-b-lg">
          <h3 class="font-bold text-2xl lg:text-3xl line-clamp-3"><%= feature.title%></h3>
          <div class="font-semibold text-sm">
            <%= I18n.localize(feature.notam_date, :format => '%^a %^b %-d %Y') %>
          </div>
          <div class="text-sm italic">
            <%= feature.category%>
          </div>
        </div>
      </section>
      <%end%>
    <%end%>

    <!--Side with recent articles-->
    <aside class="w-full lg:w-1/3 lg:h-screen-1/2 flex flex-col items-center lg:justify-between lg:mr-5">
      <h3 class="text-center font-semibold py-5 text-2xl text-slate-200 hidden lg:block">Recent Articles</h3>
      <% @notams.published.last(3).reverse_each do |post| %> 
        <%= link_to post, data: { turbo: false }, class: "" do%>
          <div class="flex flex-row items-center  w-full lg:rounded-lg h-24 lg:mb-0 hover:brightness-105 transition-all duration-300">
            <!--image-->
            <div class="w-2/5 flex flex-row items-center">
              <%= image_tag post.feature_image.url, class: "object-cover object-center lg:rounded-l-lg h-24 w-full", alt: "picture for article: #{post.title}"%>
              <%#= post.feature_image %><br>    
            </div>
            <div class=" pl-5 w-3/5 flex flex-col justify-center items-start h-full text-md pr-5 bg-slate-50 lg:rounded-r-lg lg:bg-gradient-to-b from-slate-50 to-slate-200  ">
              <div class="line-clamp-2 text-slate-800"><%= post.title %></div>
              <div class="font-semibold text-sm pt-1">
                <%= I18n.localize(post.notam_date, :format => '%^a %^b %-d %Y') %>
              </div>
            </div>
          </div>
        <% end %>
      <%end %>
    </aside>
  </div>

  <!--Next section with categories-->
  <div class="flex flex-col lg:flex-row lg:justify-between lg:pb-10 bg-gradient-to-r from-slate-700 to-slate-900 text-slate-200">
    <!--Category 1: Business and Marketing<-->
    <div class="lg:w-1/3 lg:mx-5 flex flex-col lg:gap-5 items-center lg:py-5 ">
      <h3 class="font-semibold py-5 lg:pt-0 lg:pb-5 text-2xl">Business and Marketing</h3>
      <% @notams.published.business_and_marketing.last(3).reverse_each do |post| %> 
        <%= render "notam_category_card", post: post %>
      <%end %>
    </div>
    <!--Category 2: Aviation and Flying-->
    <div class="lg:w-1/3 lg:mx-5 flex flex-col items-center py-5 lg:gap-5 ">
      <h3 class="font-semibold pb-5 text-2xl">Aviation and Flying</h3>
      <% @notams.published.aviation_and_flying.last(3).reverse_each do |post| %> 
        <%= render "notam_category_card", post: post %>
      <%end %>
    </div>
    <!--Category 3: News and announcements -->
    <div class="lg:w-1/3 lg:mx-5 lg:gap-5 flex flex-col lg:py-5 items-center">
      <h3 class="font-semibold pb-5 text-2xl">News and Announcements</h3>
      <% @notams.published.news_and_announcements.last(3).reverse_each do |post| %> 
        <%= render "notam_category_card", post: post %> 
      <%end %>
    </div>
  </div>
</div>

<%= render "shared/cta1" %>
<%= render "shared/footer" %>

app/views/notams/new.html.erb
<%# Head / Meta Data %>
<% title("Publish New NOTAM | Right Rudder Marketing Blog") %>
<% meta_description("Publish a new NOTAM on the Right Rudder Marketing Blog") %>
<% meta_keywords("aviation blog, flight school blog, aviation business blog, news about business aviation, flight school news") %>

<%= render "shared/navbar_nonsticky" %>

<div class="pt-10 lg:py-10 bg-slate-100">

  <%= render "form", notam: @notam %>

  <%#= link_to 'Back to notams', notams_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

<%= render "shared/footer"%>

app/views/notams/show.html.erb
<%# Head / Meta Data %>
<% title(@notam.title + " | Right Rudder Marketing Blog") %>
<% meta_description(if @notam.meta_description? then @notam.meta_description end) %>
<% meta_keywords(if @notam.meta_keywords? then @notam.meta_keywords end) %>
<%# og_image(polymorphic_url(@notam.feature_image)) # test this out later if not working. %>
<% og_image(@notam.feature_image.url) %>
<% twitter_image(@notam.feature_image.url) %>

<!--Set Page font size and limit sticky-->
<div class="text-lg bg-gradient-to-r from-slate-100 to-blue-100">
  <%= render "shared/navbar" %>

  <div class="flex flex-col items-center">
    <div class="lg:border-1 lg:w-3/5 flex flex-col lg:rounded-xl lg:my-10 border-slate-300 bg-slate-50">
      <!--Header-->
      <%=image_tag @notam.feature_image.url, class:"w-full object-cover object-center lg:rounded-t-xl", alt: "picture for article: #{@notam.title}"%>
      <!--Text-->
      <div class="">
        <div class="p-3">
          <h2 class="font-bold text-3xl"><%= @notam.title %></h2>
          <div class="text-md font-semibold"><%= @notam.category %></div>      
          <div class="text-sm font-semibold"><%= I18n.localize(@notam.notam_date, :format => '%^a %^b %-d %Y') %></div>
          <div class="text-sm italic">Written by <%= @notam.author%></div>          
        </div>
        <%# Shown only when logged in %>
        <% if admin_signed_in? %>
        <hr class="border-slate-300">        
        <div class="p-3">
          <div>Status: <span class="italic"><%= @notam.status %></span></div>
          <div class="flex flex-row gap-3">
            <%= link_to 'Edit this post', edit_notam_path(@notam), class: "font-semibold hover:underline", data: { turbo: false } %>
            <span class="hidden"> | </span>
            <%= button_to 'Delete this post', notam_path(@notam), method: :delete, class: " font-semibold hover:underline" %>
          </div>
        </div>
        <hr class="border-slate-300">
        <%end%>
      </div>
      
      <!--Content-->
      <div class="p-3 no-tailwindcss-base ">
        <%= raw @notam.notam_body %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/cta1" %>
<%= render "shared/footer" %>

app/views/notams/webinars.html.erb
<%# Head / Meta Data %>
<% title("The Right Rudder Marketing Webinar Series") %>
<% meta_description("The Right Rudder Marketing Webinar Series is a series created to inspire flight schools to achieve optimal success in their businesses.") %>
<% meta_keywords("Right Rudder Marketing, Blog, aviation webinar, aviation marketing, aviation business marketing ideas") %>
<% og_image(image_url("rrm-notams-trans.webp")) %>
<% twitter_image(image_url("rrm-notams-trans.webp")) %>


<!--Set Page font size and limit sticky-->
<div class="text-lg">
  <%= render "shared/navbar" %>
  <!--Header Section-->
  <section class="grid place-items-center bg-gradient-to-r from-slate-100 to-blue-100 lg:to-blue-200">
    <div class="py-20 flex flex-col lg:flex-row-reverse lg:w-5/6">
      <!--Blog image-->
      <div class="grid place-items-center ">
        <%= image_tag "webinartrans.webp", class: "w-4/5"%>
      </div>
      
      <!--Text about webinar-->
      <div class="px-5 lg:px-0 lg:w-3/4">
        <h1 class="text-5xl font-bold text-center pt-20 pb-5">Right Rudder Marketing Webinar Series</h1>
        <h2 class=" text-xl lg:text-2xl font-semibold text-center pb-5 italic">Hosted by Tim Jedrek</h2>
        <p class="pb-5 text-md px-10 lg:text-xl text-left">The Right Rudder Marketing Webinar Series is a series created to inspire flight schools to achieve optimal success in their businesses.</p>
        <p class="pb-5 text-md px-10 lg:text-xl text-left">Tim Jedrek is a digital marketing expert and a pilot.  Tim Jedrek has years of experience in management and leadership working with sales and marketing teams, decades of experience in computer science and programming, and experience working in flight schools interacting with customers and aircraft.</p>
        <p class="lg:pb-20 text-md px-10 lg:text-xl text-left">On each episode, Tim will go over topics that will help flight schools develop their very own Flight School Marketing System.  Tim will also be sitting down with industry leaders to talk about their processes, the lessons they learned, and how to find success in aviation and business.</p>
      </div>
    </div>
  </section>

  <!--Feed (@notams is already filtered down to just webinars via notam controller)-->
  <section class="bg-gradient-to-l from-slate-900 to-slate-800 lg:to-slate-700 text-slate-50">
    <div class="flex flex-col lg:flex-row">
      
      <!--Upcoming-->
      <div class="lg:w-1/2 flex flex-col items-center lg:pb-20">
        <h2 class="text-3xl font-bold py-10">Upcoming Webinars</h2>
        
        <% upcoming_webinar = @notams.upcoming.published.last %>
        <% if upcoming_webinar.present? %>
          <div class="lg:w-3/4 lg:rounded-xl bg-slate-100 text-slate-800">  
            <%= link_to upcoming_webinar, class: "" do %>
              <%= image_tag upcoming_webinar.feature_image.url, class: "lg:rounded-t-xl w-full", alt: "picture for article: #{upcoming_webinar.title}" %>
              <div class="px-5 pb-5">
                <h3 class="font-bold text-xl pt-5"><%= upcoming_webinar.title %></h3>
                <div class="pb-5 font-semibold"><%=I18n.localize(upcoming_webinar.notam_date, :format => '%^a %^b %-d %Y') %></div>
                <div class="">
                  <%
                    truncated_text = upcoming_webinar.notam_body.truncate(250)
                    if truncated_text != upcoming_webinar.notam_body
                      truncated_text += link_to "Click to read more", upcoming_webinar, class: "text-blue-700 hover:underline"
                    end
                  %>
                  <%= raw truncated_text %>
                </div>
              </div>
            <% end %>
          </div>
          
        <% else %>
          New webinar coming soon!
        <% end %>
      </div>
      
      <!--Previous-->
      <div class="lg:w-1/2 flex flex-col items-center lg:pb-20">
        <h2 class="text-3xl font-bold py-10">Previous Webinars</h2>
        <% if @notams.previous.published.present? %>
          <% @notams.previous.published.each do |post| %> 
            <div class="flex flex-row items-center  lg:w-3/4 lg:rounded-lg h-24 lg:mb-3 hover:brightness-105 transition-all duration-300">
              <%= link_to post, data: { turbo: false }, class: "flex flex-row items-center" do%>
                <!--image-->
                <div class="w-2/5 flex flex-row items-center">
                  <%= image_tag post.feature_image.url, class: "object-cover object-center lg:rounded-l-lg h-24 w-full", alt: "picture for article: #{post.title}"%>
                </div>
                <div class=" pl-5 w-3/5 flex flex-col justify-center items-start h-24 text-md pr-5 bg-slate-50 lg:rounded-r-lg lg:bg-gradient-to-b from-slate-50 to-slate-200  ">
                  <div class="line-clamp-2 text-slate-800"><%= post.title %></div>
                  <div class="font-semibold text-sm pt-1 text-slate-800">
                    <%= I18n.localize(post.notam_date, :format => '%^a %^b %-d %Y') %>
                  </div>
                </div>
              <% end %>
            </div>
          <%end%>
        <%else%>
         No webinars published yet!
        <%end%>
      </div>
    </div>

  </section>
  


<%= render "shared/cta1" %>
<%= render "shared/footer" %>