config/routes.rb
Rails.application.routes.draw do
  
  # 404/500 pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :newsletter_emails
  resources :careers
  devise_scope :admin do
    # Redirests signing out users back to sign-in
    get "admins", to: "devise/sessions#new"
  end
  
  devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }

  # homepage
  root "pages#home"
  get 'intro_video_embed', to: "pages#intro_video_embed", as: :embed_video
  get 'intro_video_embed_maint', to: "pages#intro_video_embed_maint", as: :embed_video_maint
  get 'newsletter_confirm', to: "newsletter_emails#confirm", as: :newsletter_confirm

  # Notams
  get 'notams/select_featured', to: 'notams#select_featured_notams'
  post 'uploader/image', to: 'uploader#image' #add upload image to notams 
  get 'webinars', to: 'notams#webinars'
  resources :notams

  # Webinars
  # resources :webinars
  
  # Agreement
  get 'agreements/form2', to: 'agreements#form2', as: :form2 
  resources :agreements

  ### Static pages routes

  # Menu Pages
  get 'marketing-system', to: 'pages#system'
  get 'schedule-call', to: 'pages#schedule_call'
  get 'about-us', to: 'pages#about_us'
  get 'system-video', to: 'pages#system_video'
  get 'flight-school-marketing-checklist', to: 'pages#checklist', as: "checklist"

  # Qualify Quiz
  get 'qualify_quiz', to: "pages#one", as: :quiz_start
  get 'qualify_quiz/two', to: "pages#two", as: :quiz_question_two
  get 'qualify_quiz/three', to: "pages#three", as: :quiz_question_three
  get 'qualify_quiz/four', to: "pages#four", as: :quiz_question_four
  get 'qualify_quiz/qualified', to: "pages#qualified", as: :quiz_qualified
  get 'qualify_quiz/unqualified_CFI', to: "pages#unqualified_CFI", as: :quiz_unqualified_CFI
  get 'qualify_quiz/unqualified_ad', to: "pages#unqualified_ad", as: :quiz_unqualified_ad
  get 'qualify_quiz/unqualified_capacity', to: "pages#unqualified_capacity", as: :quiz_unqualified_capacity
  get 'qualify_quiz/unqualified_service', to: "pages#unqualified_service", as: :quiz_unqualified_service


  # Offering Pages / Services
  get 'website-design', to: 'pages#website_design'
  get 'search-engine-optimization', to: 'pages#search_engine_optimization'
  get 'pay-per-click-ads', to: 'pages#pay_per_click_ads'
  get 'video-creation', to: 'pages#video_creation'
  get 'email-campaigns', to: 'pages#email_campaigns'
  get 'social-media-management', to: 'pages#social_media_management'
  get 'reputation-management', to: 'pages#reputation_management'

  # Legal Footer Pages
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'terms-of-service', to: 'pages#terms_of_service'

end

app/views/shared/_associations.html.erb
<!--Associations section-->
<section class="bg-slate-200">
  <div class="flex flex-col items-center">
    <div class="pt-10">
      <h2 class="text-xl font-semibold italic text-center px-16">The Gateway Flight Training team are proud members of the following organizations</h2>
    </div>
    <div class="flex flex-col lg:flex-row justify-center items-center gap-10 lg:gap-10 px-20 md:px-48  lg:px-5 pt-10 pb-20 lg:py-10">
      
      <!--FAAST-->
      <%= link_to "https://www.faasafety.gov", class: "lg:w-1/5", target: :blank do %>
        <%= image_tag "FAAST.webp", alt: "Federal Aviation Safety Team Logo", class: "hover:scale-105 transition-all duration-300 h-48"%>
      <%end%>
      <!--SAFE-->
      <%= link_to "https://safepilots.org", class: "lg:w-1/5", target: :blank do %>
        <%= image_tag "SAFE.webp", alt: "Society of Aviation and Flight Educators logo", class: "hover:scale-105 transition-all duration-300 px-5  h-44"%>
      <%end%>
      <!--NAFI-->
      <%= link_to "https://www.nafinet.org/sponsors", class: "lg:w-1/5", target: :blank do %>
        <%= image_tag "nafi.webp", alt: "National Association of Flight Instructors logo", class: "hover:scale-105 transition-all duration-300 px-5"%>
      <%end%>
      <!--NBAA-->
      <%= link_to "https://nbaa.org", class: "lg:w-1/5", target: :blank do %>
        <%= image_tag "nbaa.webp", alt: "National Business Aviation Association logo", class: "hover:scale-105 transition-all duration-300"%>
      <%end%>
      <!--MPA-->
      <%= link_to "https://mopilots.org", class: "lg:w-1/5", target: :blank do %>
        <%= image_tag "mpa.webp", alt: "Missouri Pilots Association logo", class: "hover:scale-105 transition-all duration-300 px-5"%>
      <%end%>
      
    </div>
  </div>
</section>

app/views/shared/_copyright_social_footer.html.erb
<!--Copyright and social-->
<section class="bg-stone-700 text-slate-300 py-5 lg:pl-9 text-center lg:text-left flex flex-col-reverse lg:flex-row lg:justify-between lg:items-center">
  <div>
    <!--Desktop-->
    <div class="hidden lg:block">
      Copyright <%= Date.today.year %> <%=link_to root_path, class: "hover:underline" do%>Gateway Flight Training, LLC<%end%>.  All Rights Reserved.
    </div>
    <!--Mobile-->
    <div class="lg:hidden">
      Copyright <%= Date.today.year %> <%=link_to root_path, class: "hover:underline" do%>Gateway Flight Training, LLC<%end%>.  <br>All Rights Reserved.
    </div> 
    <div class="">
      <%=link_to privacy_policy_path, class: "hover:underline" do%>Privacy Policy<%end%> | <%= link_to terms_of_service_path, class: "hover:underline" do%>Terms of Service<%end%>
    </div>
  </div>
  <div class="flex flex-row justify-center gap-5 lg:gap-3 lg:pr-10 pb-3 lg:pb-0">
    <div class="hover:underline">
      <%=link_to "https://wa.me/13143582100", target: :blank do%>
        <%= image_tag "whatsappicon.webp", alt: "whatsapp icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "https://www.facebook.com/rightruddermarketing", target: :blank do%>
        <%= image_tag "facebookicon.webp", alt:"facebook icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "https://www.instagram.com/rightruddermarketing/", target: :blank do%>
        <%= image_tag "instagramicon.webp", alt:"instagram icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "https://www.youtube.com/@rightruddermarketing", target: :blank do%>
        <%= image_tag "youtubeicon.webp", alt:"youtube icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "https://twitter.com/rightruddermktg", target: :blank do%>  
        <%= image_tag "twittericon.webp", alt:"twitter icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "http://linkedin.com/company/rightruddermarketing", target: :blank do%>
        <%= image_tag "linkedinicon.webp", alt:"linkedin icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_cta1.html.erb
<section class="w-full h-screen bg-head bg-cover bg-center flex justify-center items-center">
  <div class="flex flex-col justify-center items-center drop-shadow-2xl" x-data>
      <h2 class="w-4/5 font-bold text-3xl sm:text-5xl lg:text-7xl"><span class="text-red-800">Fly with experienced safe aviators</span> that know the flight training industry.</h2>
      <p class="w-4/5 py-5 lg:py-10 text-xl lg:text-2xl font-semibold">We are a team of aviators that are experts in the flight training industry.  We've been in the business for decades and have the experience to get you safely in the air.  Start your flight training today and see what we're talking about by scheduling a discovery flight.</p>
      <div class="opacity-0 duration-[1500ms] translate-y-24 text-center w-full flex flex-col items-start" x-intersect="$el.classList.add('opacity-100', 'translate-y-1', 'z-0')">
        <%=link_to schedule_call_path, class: "mx-auto" do%>
          <div class="bg-red-800 font-semibold hover:bg-red-700 hover:scale-105 text-white text-xl lg:text-3xl rounded-lg text-center py-2 px-5 transition-all duration-300">
            SEND US MESSAGE
          </div>
        <% end %>
      </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<!--Footer-->
<section class="w-full bg-red-900 text-slate-100">
  <div class="flex flex-col lg:flex-row justify-center items-start pt-10">
    <!--Logo and mission-->
    <div class="lg:w-1/4 flex flex-col justify-center lg:justify -start px-10">
      <%= image_tag "gatewaylogo_white.webp", alt: "Gateway Logo White", class: "w-56"%>
      <p class="pt-7 lg:pr-0 pr-10">
        Safety in aviation through education.  We are a team of knowledgeable and expierenced aviators with a priority in safety.  Our mission is serve the St. Louis aviation community with our aviation knowledge and expertise.
      </p>
    </div>
    <!--Links-->
    <div class="lg:w-1/4 flex flex-col justify-center lg:pl-24 pl-10 pr-8">
      <h3 class="font-bold text-xl pt-10 pb-5 lg:pb-10">Website Links</h3>
      <ul class="font-semibold ">
        <li class="pb-3"><%= link_to schedule_call_path, class: "hover:underline" do %>Flight Training<%end%></li>        
        <li class="pb-3"><%= link_to "https://rightruddermarketing.com/notams/5-tips-to-grow-your-flight-school", data: { turbo: false }, class: "hover:underline" do %>Maintenance<%end%></li>
        <li class="pb-3"><%= link_to webinars_path, data: { turbo: false }, class: "hover:underline" do %>News and Announcements<%end%></li>
        <li class="pb-3"><%= link_to marketing_system_path, data: { turbo: false } , class: "hover:underline" do %>About Us<%end%></li>
        <li class="pb-3"><%= link_to about_us_path, data: { turbo: false }, class: "hover:underline" do %>Contact Us<%end%></li>
        <li class="pb-3"><%= link_to careers_path, data: { turbo: false }, class: "hover:underline" do %>Flight Scheduler<%end%></li>
      </ul>
    </div>
    <!--Contact-->
    <div class="lg:w-1/4 flex flex-col justify-center lg:px-3 pl-10">
      <h3 class="font-bold text-xl pt-10 pb-3  lg:pb-10">Contact Us</h3>
      <ul class="pb-5 w-full">
        <li class="pb-5">
          <div class="flex flex-row">
            <div class="pr-3">
              <%= image_tag "pin.webp", alt: "map pin", class: "h-5 invert pt-1"%>
            </div>
            14301 Creve Coeur Airport Road<br>
            Hangar N3<br>
            Maryland Heights, MO 63146<br>
          </div>
        </li>
        <li class="pb-5">
          <div class="flex flex-row">
            <div class="pr-3">
              <%= image_tag "phone.webp", alt: "phone icon", class: "h-5 invert pt-1" %>
            </div>
            <%= link_to "1-314-780-7899", "tel:1-314-780-7899" %>
          </div>
        </li>
        <li class="pb-5">
          <div class="flex flex-row">
            <div class="pr-3"><%= image_tag "email.webp", alt: "email icon", class: "h-5 invert pt-1 object-contain" %></div>
            <p>
              <%= mail_to "info@gatewayflight.com", class: "hover:underline"%>
            </p>
          </div>
        </li>
      </ul>
    </div>
    <!--News Letter-->
    <div class="lg:w-1/4 w-full flex flex-col mt-10 lg:my-10 justify-center lg:px-5 lg:mr-5">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199216.56948954644!2d-90.7874590671875!3d38.7233441!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87df2c3d6da8c597%3A0x858179118d0ef2b8!2sGateway%20Flight%20Training!5e0!3m2!1sen!2sus!4v1677399534070!5m2!1sen!2sus" class="aspect-video h-72" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>
</section>
<%= render "shared/messenger"%>
<%= render "shared/copyright_social_footer" %>

app/views/shared/_messenger.html.erb
<!-- Messenger Chat Plugin Code -->
    <div id="fb-root"></div>

    <!-- Your Chat Plugin code -->
    <div id="fb-customer-chat" class="fb-customerchat">
    </div>

    <script>
      var chatbox = document.getElementById('fb-customer-chat');
      chatbox.setAttribute("page_id", "103448132589651");
      chatbox.setAttribute("attribution", "biz_inbox");
    </script>

    <!-- Your SDK code -->
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          xfbml            : true,
          version          : 'v15.0'
        });
      };

      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>

app/views/shared/_navbar.html.erb
<%# I wanted to create a sticky navbar and a non sticky nav bar but I already created several pages 
which render to this so rather than make navbar_sticky and navbar_nonsticky, I decided to cut everything 
out in here and into partials.  That way I can keep the same filename in this partial and create a new
partial navbar_nonsticky which still renders the same code as this but isn't sticky.  Gotta keep it DRY bro.
%>

<% if notice %>
  <p class="sticky bg-green-100 text-green-700 px-5 py-1 text-center lg:text-left"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="sticky bg-red-100 text-red-700 px-5 py-1 text-center lg:text-left"><%= alert %></p>
<% end %>

<% if !admin_signed_in? %>
  <!--Book now (mobile screens)-->
  <nav class="top-0 z-50">
    <%= render "shared/navbar_orange_call"%>
  </nav>
<%end%>

<!--Top Menu-->
<nav class="sticky top-0 w-full bg-white drop-shadow-2xl opacity-90 z-50" x-data="{ menu: false }">
    <%= render "shared/navbar_menu"%>
</nav>

app/views/shared/_navbar_absolute.html.erb
<div class="absolute w-full">
  <!--Top Menu-->
  <nav class="top-0 w-full bg-white drop-shadow-2xl z-50" x-data="{ menu: false }">
      <%= render "shared/navbar_menu"%>
  </nav>
</div>

app/views/shared/_navbar_menu.html.erb
<!--Flex Container-->
<div class="flex flex-row items-center justify-between py-0 lg:pt-4 lg:pb-6">
  <!--Logo Box-->
  <div class="hover:brightness-125 transition-all duration-300">
    <%= link_to root_path, data: { turbo: false } do %>
      <%= image_tag "gatewaylogo_red400.webp", alt:"Gateway Flight School Logo", class: "h-14 lg:h-20 ml-5" %>
    <% end %>
  </div>
  <!--Mobile Hamburger-->
  <div class="lg:hidden text-4xl p-5" x-on:click="menu = ! menu">
    ☰
  </div>
  
  <div class="hidden mr-5 mt-4 text-lg font-bold lg:flex lg:flex-row lg:items-center uppercase italic">
    <%= link_to "Home", root_path, data: { turbo: false }, class: "px-3 hover:text-red-700 transition-all duration-300" %>
    <%= link_to "Flight Training", marketing_system_path, data: { turbo: false }, class: "px-3 hover:text-red-800 transition-all duration-300" %>
    <%= link_to "Maintenance", notams_path, data: { turbo: false }, class: "px-3 hover:text-red-800 transition-all duration-300" %>
    <%= link_to "Financing", notams_path, data: { turbo: false }, class: "px-3 hover:text-red-800 transition-all duration-300" %>
    <%= link_to "About Us", notams_path, data: { turbo: false }, class: "px-3 hover:text-red-800 transition-all duration-300" %>
    <%= link_to "Blog", notams_path, data: { turbo: false }, class: "px-3 hover:text-red-800 transition-all duration-300" %>
    <%= link_to "Flight Schedule", schedule_call_path, class: "bg-red-800 hover:bg-red-700 text-white rounded-lg text-center py-2 px-5 ml-8 mr-2 transition-all duration-300 not-italic font-semibold" %>
  </div>
</div>
<!--Mobile Menu-->
<div class="absolute bg-white w-full h-screen flex flex-col justify-center pb-52" x-cloak x-show="menu" x-transition x-transition:enter.duration.600ms >
  <ul class="text-center font-semibold text-lg" x-data="{ dropdown: false }">
    <li class="py-3"><%= link_to "Home", root_path, data: { turbo: false }, class: "hover:text-blue-700 transition-all duration-300" %></li>
    <li class="py-3"><%= link_to "Our System", marketing_system_path, data: { turbo: false }, class: "hover:text-blue-700 transition-all duration-300" %></li>
    <!--Resources Menu-->
    <li class="py-3"><button class="hover:text-blue-700 transition-all duration-300" x-on:click="dropdown = ! dropdown">Resources</button></li>
    <div class="" x-cloak x-show="dropdown" x-transition x-transition:enter.duration.600ms>
      <li class="py-2"><%= link_to "Webinars", webinars_path, data: { turbo: false }, class: "hover:text-blue-700 transition-all duration-300" %></li>  
      <li class="py-2"><%= link_to "Flight School Tips", checklist_path, data: { turbo: false }, class: "hover:text-blue-700 transition-all duration-300" %></li>  
      <li class="py-2"><%= link_to "Business and Marketing Articles", notams_path, data: { turbo: false }, class: "hover:text-blue-700 transition-all duration-300" %></li>  
      <li class="py-2"><%= link_to "Growth Accelerator Session", schedule_call_path, class: "hover:text-blue-700 transition-all duration-300" %></li>  
    </div>
    <li class="py-3"><%= link_to "NOTAMs", notams_path, data: { turbo: false }, class: "hover:text-blue-700 transition-all duration-300" %></li>
    <li class="py-3"><%= link_to "Schedule Call", schedule_call_path, class: "hover:text-blue-700 transition-all duration-300" %></li>
  </ul>
</div>

app/views/shared/_navbar_nonsticky.html.erb
<% if notice %>
  <p class="bg-green-100 text-green-700 px-5 py-1 text-center lg:text-left"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="bg-red-100 text-red-700 px-5 py-1 text-center lg:text-left"><%= alert %></p>
<% end %>

<% if !admin_signed_in? %>
  <!--Book now (mobile screens)-->
  <nav class="top-0 z-50">
    <%= render "shared/navbar_orange_call"%>
  </nav>

  <!--Phone and h1 tag-->
  <header class="top-0 z-50 bg-blue-900 text-white lg:flex flex-row justify-between py-2 pl-5 pr-8">
    <%= render "shared/navbar_blue_headline"%>
  </header>
<%end%>

<!--Top Menu-->
<nav class="top-0 w-full bg-white drop-shadow-2xl z-50" x-data="{ menu: false }">
    <%= render "shared/navbar_menu"%>
</nav>

app/views/shared/_navbar_orange_call.html.erb
<%= link_to schedule_call_path do %>
  <header class=" bg-red-900 text-white lg:hidden flex-row justify-between py-2 pl-5 pr-8">
    <div class="font-semibold text-sm text-center grid place-items-center">
      Click HERE for Online Flight Scheduler
    </div>
  </header>
<% end %> 

app/views/shared/_user_menu.html.erb
<div x-data="{ usermenu: false }" class="font-mono ">
  <div class="w-full lg:h-10 h-16 bg-slate-700 flex flex-row justify-between items-center sticky z-50">
    <div class="pl-5 text-slate-100">
      Welcome, admin <%#= current_admin.email %>
    </div>

    <!--Hamburger button-->
    <button @click="usermenu = ! usermenu;" class="text-slate-500 text-4xl pr-5 pb-1 hover:text-slate-800 lg:hidden">
      ☰
    </button >
    
    <!--desktop menu-->
    <div class="hidden lg:flex lg:flex-row lg:pr-10 xl:pr-5">
      <!--Button-->
      <%= button_to 'New Webinar', new_notam_path, method: :get, data: { turbo: false }, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <%= button_to 'New NOTAM', new_notam_path, method: :get, data: { turbo: false }, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <%= button_to 'NOTAM drafts', root_path, method: :get, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <%= button_to 'Newsletter', root_path, method: :get, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <%= button_to 'Support Tickets', root_path, method: :get, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <%= button_to 'Careers', root_path, method: :get, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <%= button_to 'Sign Out', destroy_admin_session_path, method: :delete, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
    </div>
  </div>

    <!--Mobile Menu--->
    <div x-cloak x-show="usermenu" x-transition.duration.200ms class="bg-slate-700 flex flex-col justify-start items-center pb-10 z-50">
      <!--Spacer-->
      <div class="h-12"></div>
      <%= button_to 'New Webinar', new_notam_path, method: :get, data: { turbo: false }, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'New NOTAM', new_notam_path, method: :get, data: { turbo: false }, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'NOTAM drafts', root_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Newsletter', root_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Support Tickets', root_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Careers', root_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Sign Out', destroy_admin_session_path, method: :delete, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>

    <!--Close button-->
    <button @click="usermenu = ! usermenu;" class="leading-10 text-slate-100 hover:text-slate-400 hover:bg-slate-700 border-2 hover:border-slate-400 w-min mt-5 px-5 rounded-full py-1">
      X
    </button>

    </div>
  </div>