config/routes.rb
Rails.application.routes.draw do
  
  # 404/500 pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :newsletter_emails
  resources :careers
  devise_scope :admin do
    # Redirests signing out users back to sign-in
    get "admins", to: "devise/sessions#new"
  end
  
  devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }

  # homepage
  root "pages#home"
  get 'intro_video_embed', to: "pages#intro_video_embed", as: :embed_video
  get 'intro_video_embed_maint', to: "pages#intro_video_embed_maint", as: :embed_video_maint
  get 'newsletter_confirm', to: "newsletter_emails#confirm", as: :newsletter_confirm

  # Notams
  get 'notams/select_featured', to: 'notams#select_featured_notams'
  post 'uploader/image', to: 'uploader#image' #add upload image to notams 
  get 'webinars', to: 'notams#webinars'
  resources :notams

  # Webinars
  # resources :webinars
  
  # Agreement
  get 'agreements/form2', to: 'agreements#form2', as: :form2 
  resources :agreements

  ### Static pages routes

  # Menu Pages
  get 'marketing-system', to: 'pages#system'
  get 'schedule-call', to: 'pages#schedule_call'
  get 'about-us', to: 'pages#about_us'
  get 'system-video', to: 'pages#system_video'
  get 'flight-school-marketing-checklist', to: 'pages#checklist', as: "checklist"

  # Qualify Quiz
  get 'qualify_quiz', to: "pages#one", as: :quiz_start
  get 'qualify_quiz/two', to: "pages#two", as: :quiz_question_two
  get 'qualify_quiz/three', to: "pages#three", as: :quiz_question_three
  get 'qualify_quiz/four', to: "pages#four", as: :quiz_question_four
  get 'qualify_quiz/qualified', to: "pages#qualified", as: :quiz_qualified
  get 'qualify_quiz/unqualified_CFI', to: "pages#unqualified_CFI", as: :quiz_unqualified_CFI
  get 'qualify_quiz/unqualified_ad', to: "pages#unqualified_ad", as: :quiz_unqualified_ad
  get 'qualify_quiz/unqualified_capacity', to: "pages#unqualified_capacity", as: :quiz_unqualified_capacity
  get 'qualify_quiz/unqualified_service', to: "pages#unqualified_service", as: :quiz_unqualified_service


  # Offering Pages / Services
  get 'website-design', to: 'pages#website_design'
  get 'search-engine-optimization', to: 'pages#search_engine_optimization'
  get 'pay-per-click-ads', to: 'pages#pay_per_click_ads'
  get 'video-creation', to: 'pages#video_creation'
  get 'email-campaigns', to: 'pages#email_campaigns'
  get 'social-media-management', to: 'pages#social_media_management'
  get 'reputation-management', to: 'pages#reputation_management'

  # Legal Footer Pages
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'terms-of-service', to: 'pages#terms_of_service'

end

app/views/pages/qualify_quiz/four.html.erb
<%= turbo_frame_tag "frame1", class: "" do %>
<div class="flex flex-col lg:flex-row items-center justify-between">
  <!--Question-->
  <div class="pb-10 lg:pb-0">
    Does your flight school prioritize safety and provide quality service and flight instruction?
  </div>
  <!--buttons-->
  <div class="flex flex-row lg:w-min justify-center gap-5 lg:ml-10">
    <%= link_to "Yes", quiz_qualified_path, class: "w-20 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
    <%= link_to "No", quiz_unqualified_service_path, class: "w-20 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
  </div>
</div>
<% end %>

app/views/pages/qualify_quiz/one.html.erb
<%# Head / Meta Data %>
<% title("Does Your Flight School Qualify? | Right Rudder Marketing") %>
<% meta_description("See if your flight school qualifies to work with Right Rudder Marketing.  Our clients need to be ready to for more work.  Our Flight School Marketing System will bring in more students pilots to flight school!") %>
<% meta_keywords("keep CFI busy, fill flight school calendar, rent out more planes, get more student pilots, grow aviation business, private pilot training") %>

<%= render "shared/navbar" %>

<section class="flex flex-col items-center py-10 lg:py-40">
  <h1 class="pb-10 font-bold text-2xl text-center px-3">See if your flight school qualifies</h1>

  <%= turbo_frame_tag "frame1", class: "w-4/5 lg:w-2/5 border-2 rounded-xl p-5 " do %>
  <div class="flex flex-col lg:flex-row items-center justify-between">
    <!--Question-->
    <div class="pb-10 lg:pb-0">
      Do you have a minimum of two CFIs at your flight school?
    </div>
    <!--buttons-->
    <div class="flex flex-row justify-center gap-5 w-min lg:ml-10">
      <%= link_to "Yes", quiz_question_two_path, class: "w-20 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
      <%= link_to "No", quiz_unqualified_CFI_path, class: "w-20 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
    </div>
  </div>
  <% end %>
</section>

<%= render "shared/footer"%>

app/views/pages/qualify_quiz/qualified.html.erb
<%= turbo_frame_tag "frame1" do %>
  <!--Question-->
  <div class="pb-10">
    You're flight school qualifies!
    <br>
    <br>
    Click continue below to schedule a call with the team at Right Rudder Marketing and let's take your flight school to the next level!
  </div>
  <!--buttons-->
  <div class="flex flex-row w-full justify-center gap-5">
    <%= link_to "Continue", schedule_call_path, data: { turbo_frame: "_top" }, class: "w-30 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
  </div>
<% end %>

app/views/pages/qualify_quiz/three.html.erb
<%= turbo_frame_tag "frame1", class: "" do %>
<div class="flex flex-col lg:flex-row items-center justify-between">
  <!--Question-->
  <div class="pb-10 lg:pb-0">
    Does your flight school have the capacity to handle more students?
  </div>
  <!--buttons-->
  <div class="flex flex-row lg:w-min justify-center gap-5 lg:ml-10">
    <%= link_to "Yes", quiz_question_four_path, class: "w-20 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
    <%= link_to "No", quiz_unqualified_capacity_path, class: "w-20 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
  </div>
</div>
<% end %>

app/views/pages/qualify_quiz/two.html.erb
<%= turbo_frame_tag "frame1", class: "" do %>
<div class="flex flex-col lg:flex-row items-center justify-between">
  <!--Question-->
  <div class="pb-10 lg:pb-0">
    Are you actively advertising to generate more business?
  </div>
  <!--buttons-->
  <div class="flex flex-row lg:w-min justify-center gap-5 lg:ml-10">
    <%= link_to "Yes", quiz_question_three_path, class: "w-20 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
    <%= link_to "No", quiz_unqualified_ad_path, class: "w-20 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
  </div>
</div>
<% end %>

app/views/pages/qualify_quiz/unqualified_CFI.html.erb
<%= turbo_frame_tag "frame1" do %>
  <!--Question-->
  <div class="pb-10 lg:pb-0">
    Unfortunately, your flight school does not qualify.  Using our Flight School Marketing System, it's expected that many more students will become interested with training at your flight school.  One man teams will more than likely not have the capacity to handle this much new volume.
    <br>
    <br>
    If you'd like to continue to see what other criteria is required, click continue below.
    <br>
    <br>
  </div>
  <!--buttons-->
  <div class="flex flex-row w-full justify-center gap-5">
    <%= link_to "Continue", quiz_question_two_path, class: "w-30 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
  </div>
<% end %>

app/views/pages/qualify_quiz/unqualified_ad.html.erb
<%= turbo_frame_tag "frame1" do %>
  <!--Question-->
  <div class="pb-10">
    Unfortunately, your flight school does not qualify. Advertising is an investment to your business and is the foundation of Right Rudder Marketing's services.  Advertising comes many different forms and methods and you might already be advertising.  Having a website or posting on a social media profile can be a form of advertising.
    <br>
    <br>
    If you're ready start advertising to grow your flight school and attract more student pilots, click continue below.
    <br>
  </div>
  <!--buttons-->
  <div class="flex flex-row w-full justify-center gap-5">
    <%= link_to "Continue", quiz_question_three_path, class: "w-30 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
  </div>
<% end %>

app/views/pages/qualify_quiz/unqualified_capacity.html.erb
<%= turbo_frame_tag "frame1" do %>
  <!--Question-->
  <div class="pb-10 lg:pb-0">
    Unfortunately, your flight school does not qualify.  Using our Flight School Marketing System, it's expected that many more students will become interested with training at your flight school.  If your flight school cannot handle additional capacity, then you're setting future student pilots up for failure.
    <br>
    <br>
    If you think you'd be able to handle additional student pilots at your flight school and you'd like to continue to see what other criteria is required, click continue below.
    <br>
    <br>
  </div>
  <!--buttons-->
  <div class="flex flex-row w-full justify-center gap-5">
    <%= link_to "Continue", quiz_question_four_path, class: "w-30 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
  </div>
<% end %>

app/views/pages/qualify_quiz/unqualified_service.html.erb
<%= turbo_frame_tag "frame1" do %>
  <!--Question-->
  <div class="pb-10 lg:pb-0">
    Unfortunately, your flight school does not qualify.  If you're flight school is not making safety a priority and is not providing quality service and flight instruction, then you're setting future student pilots up for failure.  We apologize that we are unable to work with you at this time.
    <br>
    <br>
  </div>
  <!--buttons-->
  <div class="flex flex-row w-full justify-center gap-5">
    <%= link_to "Return", marketing_system_path, data: { turbo_frame: "_top" }, class: "w-30 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-center py-2 px-5 transition-all duration-300" %>
  </div>
<% end %>