config/routes.rb
Rails.application.routes.draw do
  
  # 404/500 pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :newsletter_emails
  resources :careers
  devise_scope :admin do
    # Redirests signing out users back to sign-in
    get "admins", to: "devise/sessions#new"
  end
  
  devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }

  # homepage
  root "pages#home"
  get 'intro_video_embed', to: "pages#intro_video_embed", as: :embed_video
  get 'intro_video_embed_maint', to: "pages#intro_video_embed_maint", as: :embed_video_maint
  get 'newsletter_confirm', to: "newsletter_emails#confirm", as: :newsletter_confirm

  # Notams
  get 'notams/select_featured', to: 'notams#select_featured_notams'
  post 'uploader/image', to: 'uploader#image' #add upload image to notams 
  get 'webinars', to: 'notams#webinars'
  resources :notams

  # Webinars
  # resources :webinars
  
  # Agreement
  get 'agreements/form2', to: 'agreements#form2', as: :form2 
  resources :agreements

  ### Static pages routes

  # Menu Pages
  get 'marketing-system', to: 'pages#system'
  get 'schedule-call', to: 'pages#schedule_call'
  get 'about-us', to: 'pages#about_us'
  get 'system-video', to: 'pages#system_video'
  get 'flight-school-marketing-checklist', to: 'pages#checklist', as: "checklist"

  # Qualify Quiz
  get 'qualify_quiz', to: "pages#one", as: :quiz_start
  get 'qualify_quiz/two', to: "pages#two", as: :quiz_question_two
  get 'qualify_quiz/three', to: "pages#three", as: :quiz_question_three
  get 'qualify_quiz/four', to: "pages#four", as: :quiz_question_four
  get 'qualify_quiz/qualified', to: "pages#qualified", as: :quiz_qualified
  get 'qualify_quiz/unqualified_CFI', to: "pages#unqualified_CFI", as: :quiz_unqualified_CFI
  get 'qualify_quiz/unqualified_ad', to: "pages#unqualified_ad", as: :quiz_unqualified_ad
  get 'qualify_quiz/unqualified_capacity', to: "pages#unqualified_capacity", as: :quiz_unqualified_capacity
  get 'qualify_quiz/unqualified_service', to: "pages#unqualified_service", as: :quiz_unqualified_service


  # Offering Pages / Services
  get 'website-design', to: 'pages#website_design'
  get 'search-engine-optimization', to: 'pages#search_engine_optimization'
  get 'pay-per-click-ads', to: 'pages#pay_per_click_ads'
  get 'video-creation', to: 'pages#video_creation'
  get 'email-campaigns', to: 'pages#email_campaigns'
  get 'social-media-management', to: 'pages#social_media_management'
  get 'reputation-management', to: 'pages#reputation_management'

  # Legal Footer Pages
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'terms-of-service', to: 'pages#terms_of_service'

end

app/models/newsletter_email.rb
require 'google_drive'
include NewsletterEmailsHelper

class NewsletterEmail < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  validates_uniqueness_of :email

  after_create :update_google_sheet

  private

  def update_google_sheet
    create_json_credentials("config/googleconfig.json")
    session = GoogleDrive::Session.from_service_account_key("config/googleconfig.json")

    spreadsheet = session.spreadsheet_by_key("1-KvGu8x8Lqqsj7DhKPLhUPXWqFbcyUHYodhs0KdsZkw").worksheets[0]
    
    # Write the data from the new instance of the newsletter_emails model
    spreadsheet.insert_rows(spreadsheet.num_rows + 1, [[self.name, self.email, "Newsletter Sign Up", self.created_at]])

    # Save the changes to the Google Sheet
    spreadsheet.save

    delete_file("config/googleconfig.json")
  end

end

app/controllers/newsletter_emails_controller.rb
class NewsletterEmailsController < ApplicationController
  before_action :set_newsletter_email, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:new, :edit, :create, :update, :confirm]
  invisible_captcha only: [:create, :update], honeypot: :confirm_email

  # GET /newsletter_emails or /newsletter_emails.json
  def index
    @newsletter_emails = NewsletterEmail.all
  end

  def confirm
    render 'confirm'
  end

  # GET /newsletter_emails/1 or /newsletter_emails/1.json
  def show
  end

  # GET /newsletter_emails/new
  def new
    @newsletter_email = NewsletterEmail.new
  end

  # GET /newsletter_emails/1/edit
  def edit
  end

  # POST /newsletter_emails or /newsletter_emails.json
  def create
    @newsletter_email = NewsletterEmail.new(newsletter_email_params)

    respond_to do |format|
      if @newsletter_email.save
        format.html { redirect_to newsletter_confirm_path, notice: @newsletter_email.name }
        format.json { render :show, status: :created, location: @newsletter_email }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newsletter_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletter_emails/1 or /newsletter_emails/1.json
  def update
    respond_to do |format|
      if @newsletter_email.update(newsletter_email_params)
        format.html { redirect_to newsletter_email_url(@newsletter_email), notice: "Newsletter email was successfully updated." }
        format.json { render :show, status: :ok, location: @newsletter_email }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newsletter_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletter_emails/1 or /newsletter_emails/1.json
  def destroy
    @newsletter_email.destroy

    respond_to do |format|
      format.html { redirect_to newsletter_emails_url, notice: "Newsletter email was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter_email
      @newsletter_email = NewsletterEmail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newsletter_email_params
      params.require(:newsletter_email).permit(:name, :email)
    end
end

app/helpers/newsletter_emails_helper.rb
module NewsletterEmailsHelper

  def create_json_credentials(path)

    credentials = {
      "type": ENV['TYPE'],
      "project_id": ENV['PROJECT_ID'],
      "private_key_id": ENV['PRIVATE_KEY_ID'],
      "private_key": ENV['PRIVATE_KEY'],
      "client_email": ENV['CLIENT_EMAIL'],
      "client_id": ENV['CLIENT_ID'],
      "auth_uri": ENV['AUTH_URI'],
      "token_uri": ENV['TOKEN_URI'],
      "auth_provider_x509_cert_url": ENV['AUTH_PROVIDER_X509_CERT_URL'],
      "client_x509_cert_url": ENV['CLIENT_X509_CERT_URL']
    }
  
    File.open(path, 'w') do |f|
      f.write(credentials.to_json)
    end
  
    path
  end

  def delete_file(path)
    File.open(path, 'w') do |f|
      f.write(" ")
    end
  end
  
end

app/views/newsletter_emails/_checklist_dl_form.html.erb
<%= form_with(model: @newsletter_email, class: "contents") do |form| %>
  <% if @newsletter_email.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 text-sm font-medium rounded-lg mb-5">
      <h2><%= pluralize(@newsletter_email.errors.count, "error") %> prohibited you from signing up:</h2>

      <ul>
        <% @newsletter_email.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="w-full">
    <div class="mb-5">
      <%= form.text_field :name, placeholder: "Name", class: " shadow text-black rounded-md border border-gray-200 focus:border-orange-500 focus:ring-orange-500 px-3 py-2 w-full" %>
    </div>
    <div class="mb-5">
      <%= form.email_field :email, placeholder: "Email", class: " shadow text-black rounded-md border border-gray-200 focus:border-orange-500 focus:ring-orange-500 px-3 py-2 w-full"  %>
    </div>
    <div class="inline">
      <%= form.submit "Download", class: "rounded-lg py-2 bg-orange-500 hover:bg-orange-600 transition-all duration-300 text-white text-lg inline-block font-bold cursor-pointer w-full" %>
    </div>
  </div>

  <p class="py-5">
  Please enter your information to download your checklist.
  </p>
<% end %>

app/views/newsletter_emails/_form.html.erb
<%= form_with(model: @newsletter_email, class: "contents") do |form| %>
  <% if @newsletter_email.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 text-sm font-medium rounded-lg mb-5">
      <h2><%= pluralize(@newsletter_email.errors.count, "error") %> prohibited you from continuing:</h2>

      <ul>
        <% @newsletter_email.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="w-full">
    <div class="mb-5">
      <%= form.text_field :name, placeholder: "Name", class: " shadow text-black rounded-md border border-gray-200 focus:border-orange-500 focus:ring-orange-500 px-3 py-2 w-full" %>
    </div>
    <div class="flex flex-row items-center gap-3">
      <div class="w-3/4">
        <%= form.email_field :email, placeholder: "Email", class: " shadow text-black rounded-md border border-gray-200 focus:border-orange-500 focus:ring-orange-500 px-3 py-2 w-full"  %>
      </div>
      <%= invisible_captcha :confirm_email, :newsletter_email %>
      <div class="inline w-1/4">
        <%= form.submit "Submit", class: "rounded-lg py-2 bg-orange-500 hover:bg-orange-600 transition-all duration-300 text-white text-lg inline-block font-bold cursor-pointer w-full" %>
      </div>
    </div>
  </div>

<% end %>

app/views/newsletter_emails/_newsletter_email.html.erb
<div id="<%= dom_id newsletter_email %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= newsletter_email.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= newsletter_email.email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this newsletter email", newsletter_email, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this newsletter email', edit_newsletter_email_path(newsletter_email), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/newsletter_emails/confirm.html.erb
<%= turbo_frame_tag "frame3", class: "w-full" do %>
  <div class="mb-10">
    Thank you, <%= notice %>, for joining our newsletter!  You are now subscribed.
  </div>
<% end %>

app/views/newsletter_emails/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing newsletter email</h1>

  <%= render "form", newsletter_email: @newsletter_email %>

  <%= link_to "Show this newsletter email", @newsletter_email, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to newsletter emails", newsletter_emails_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/newsletter_emails/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Newsletter emails</h1>
    <%= link_to 'New newsletter email', new_newsletter_email_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="newsletter_emails" class="min-w-full">
    <%= render @newsletter_emails %>
  </div>
</div>

app/views/newsletter_emails/new.html.erb
<%= turbo_frame_tag "frame3", class: "w-full" do %>
<div class="">
  <!--<h1 class="font-bold text-4xl">New newsletter email</h1>-->

  <%= render "form", newsletter_email: @newsletter_email %>

  <%#= link_to 'Back to newsletter emails', newsletter_emails_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
<%end%>

app/views/newsletter_emails/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @newsletter_email %>

    <%= link_to 'Edit this newsletter_email', edit_newsletter_email_path(@newsletter_email), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this newsletter_email', newsletter_email_path(@newsletter_email), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to newsletter_emails', newsletter_emails_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>